### ISSUE TITLE
contextualize.py takes long time and never stop

### ISSUE THREAD

**Issue by anaivebird** [dheeraj7596/ConWea#1]
It runs for more than 5 hours, and keep running with info "Finished clustering words: 114100", how long will it cost to stop?

my command is python contextualize.py --dataset_path ./data/nyt/fine/ --temp_dir /content/tmp/ --gpu_id 0

4 core cpu with P100 16G

**Comment by dheeraj7596** [comment]
It takes some time to run because it gets BERT vectors and clusters iteratively. If you have a gpu, please run on it. It'd be faster.
