### ISSUE TITLE
Why there are 7 classes in 20News Course? 

### ISSUE THREAD

**Issue by zhanglu-cst** [dheeraj7596/ConWea#3]
Why there are 7 classes? 
There are 6 classes in course as stated in your paper.

**Comment by dheeraj7596** [comment]
The 20newsgroup dataset can be split into 7 coarse-grained classes based on the prefix and 6 coarse-grained classes using the website. I have added seed words for 6 coarse-grained classes.

**Comment by zhanglu-cst** [comment]
> The 20newsgroup dataset can be split into 7 coarse-grained classes based on the prefix and 6 coarse-grained classes using the website. I have added seed words for 6 coarse-grained classes.

Is the results in your paper refers to the "6 coarse-grained classes using the website." ?

**Comment by dheeraj7596** [comment]
No, the results reported are on 7 classes and it's a typo that I mentioned 6, my bad, I am sorry.
