### ISSUE TITLE
Some question about data spilt.

### ISSUE THREAD

**Issue by zhanglu-cst** [dheeraj7596/ConWea#4]
Hello, I took a look at the code, it seems that you only split all the data into train/val and report the results on val, without using train/val/test settting and report the results on test. Is that true? 
Thank you.

**Comment by dheeraj7596** [comment]
No, there is no train/val split here. The task is, I have an unlabeled corpus and I have to label it. So, I report results on all the dataset. Please email me your questions and we can discuss them in detail. I prefer email over here as I don't check github often. My email address is available on my github.
